import { useState } from "react";
import { Donut, HBars, LineChart } from "@/components/charts";
import { Icon } from "@/components/Icon";
import {
  Badge, Banner, Button, Card, CardHeader, EmptyState, KeyValue, PageHeader, Progress, Row, SimTag, Stat,
  StatusBadge, Tabs, TableWrap, Td, Th,
} from "@/components/ui";
import { IncidentModal, InspectionModal, NearMissModal } from "@/components/workflow/FleetWorkflows";
import { dateSA, num, pct, time24 } from "@/lib/format";
import { useRouter } from "@/router";
import { useStore } from "@/state/store";
import { cn } from "@/utils/cn";

/* ====================== SAFETY DASHBOARD ====================== */

export function SafetyPage() {
  const { state } = useStore();
  const { navigate } = useRouter();
  const [incidentOpen, setIncidentOpen] = useState(false);
  const [nearMissOpen, setNearMissOpen] = useState(false);

  const todayIncidents = state.incidents.filter((i) => i.date === state.today);
  const preventable = state.incidents.filter((i) => i.preventable).length;
  const inspectedToday = state.inspections.filter((i) => i.date === state.today).length;
  const inspectionCompliance = (inspectedToday / state.vehicles.length) * 100;
  const trainingTotal = state.drivers.length * state.drivers[0].training.length;
  const trainingDone = state.drivers.reduce((s, d) => s + d.training.filter((t) => t.status === "Completed").length, 0);
  const trainingCompliance = (trainingDone / trainingTotal) * 100;

  return (
    <>
      <PageHeader
        title="Safety Dashboard"
        description="Incidents, near misses, inspection compliance, training and simulated driving events across the fleet."
        actions={
          <>
            <Button variant="secondary" icon="eye" onClick={() => setNearMissOpen(true)}>Report near miss</Button>
            <Button variant="danger" icon="shield" onClick={() => setIncidentOpen(true)}>Report incident</Button>
          </>
        }
      />

      <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">
        <Stat label="Incidents today" value={todayIncidents.length} tone={todayIncidents.length ? "critical" : "success"} icon="alert" onClick={() => navigate("/ops/incidents")} />
        <Stat label="Open incidents" value={state.incidents.filter((i) => i.status !== "Closed").length} tone="warning" icon="folder" onClick={() => navigate("/ops/incidents")} />
        <Stat label="Preventable (all time)" value={preventable} tone={preventable ? "warning" : "success"} sub="target: zero" icon="target" />
        <Stat label="Near misses logged" value={state.nearMisses.length} icon="eye" onClick={() => navigate("/ops/near-misses")} />
        <Stat label="Inspection compliance" value={pct(inspectionCompliance)} tone={inspectionCompliance >= 95 ? "success" : "warning"} icon="clipboard" onClick={() => navigate("/ops/inspections")} />
        <Stat label="Training compliance" value={pct(trainingCompliance)} tone={trainingCompliance >= 90 ? "success" : "warning"} icon="graduation" onClick={() => navigate("/ops/training")} />
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-3">
        <Card>
          <CardHeader title="Incidents by severity" subtitle="All recorded incidents" icon="alert" />
          <div className="p-4">
            <Donut
              segments={["Low", "Medium", "High", "Critical"].map((s, i) => ({
                label: s,
                value: state.incidents.filter((x) => x.severity === s).length,
                colour: ["#12a05c", "#d97706", "#dc2626", "#7f1d1d"][i],
              }))}
              centreValue={String(state.incidents.length)}
              centreLabel="incidents"
            />
          </div>
        </Card>
        <Card>
          <CardHeader title="Near misses by risk type" subtitle="Reporting is blame-free and encouraged" icon="eye" />
          <div className="p-4">
            <HBars
              data={Array.from(new Set(state.nearMisses.map((n) => n.riskType))).map((t) => ({
                label: t,
                value: state.nearMisses.filter((n) => n.riskType === t).length,
              }))}
              colour="#2b5480"
            />
          </div>
        </Card>
        <Card>
          <CardHeader title="Safety events trend" subtitle="Daily incidents over 30 days" icon="activity" />
          <div className="p-4">
            <LineChart data={state.history.map((h) => ({ label: h.date.slice(8), value: h.incidents }))} height={170} colour="#dc2626" yMin={0} yMax={3} />
          </div>
        </Card>
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <Card>
          <CardHeader
            title="Simulated telematics events"
            subtitle="Speed, braking and acceleration events generated by the demo"
            icon="signal"
            action={<SimTag />}
          />
          <TableWrap>
            <thead><tr><Th>Vehicle</Th><Th>Event</Th><Th>Value</Th><Th>Location</Th><Th>Time</Th></tr></thead>
            <tbody>
              {state.telematics.slice(0, 10).map((t) => (
                <Row key={t.id}>
                  <Td className="font-semibold text-navy-950">{t.vehicleId}</Td>
                  <Td><Badge tone={t.type === "Speeding" || t.type === "Harsh Braking" ? "warning" : "neutral"}>{t.type}</Badge></Td>
                  <Td className="num">{t.value}</Td>
                  <Td>{t.location}</Td>
                  <Td className="num">{time24(t.time)}</Td>
                </Row>
              ))}
            </tbody>
          </TableWrap>
        </Card>
        <Card>
          <CardHeader title="Corrective actions" subtitle="What is being done about recorded incidents" icon="clipboard" />
          <ul className="divide-y divide-mist-100">
            {state.incidents.map((i) => (
              <li key={i.id} className="px-4 py-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <button onClick={() => navigate(`/ops/incidents?id=${i.id}`)} className="text-[13px] font-semibold text-navy-950 hover:underline">
                    {i.id} · {i.type}
                  </button>
                  <StatusBadge status={i.status} />
                </div>
                <p className="mt-1 text-[12.5px] text-charcoal-500">{i.correctiveAction || "Corrective action still to be captured."}</p>
              </li>
            ))}
          </ul>
        </Card>
      </div>

      <IncidentModal open={incidentOpen} onClose={() => setIncidentOpen(false)} />
      <NearMissModal open={nearMissOpen} onClose={() => setNearMissOpen(false)} />
    </>
  );
}

/* ====================== INCIDENTS ====================== */

export function IncidentsPage() {
  const { state } = useStore();
  const { params, setParam } = useRouter();
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState("All");
  const selected = state.incidents.find((i) => i.id === params.get("id"));
  const list = state.incidents.filter((i) => tab === "All" || i.status === tab);

  return (
    <>
      <PageHeader
        title="Incidents"
        description="Every safety incident recorded against a driver, vehicle or delivery, with severity and corrective action."
        actions={<Button variant="danger" icon="shield" onClick={() => setOpen(true)}>Report incident</Button>}
      />
      {selected && (
        <div className="mb-4">
          <Card>
            <CardHeader
              title={`${selected.id} · ${selected.type}`}
              subtitle={`${dateSA(selected.date)} ${selected.time} · ${selected.location}`}
              icon="alert"
              action={
                <>
                  <Badge tone={selected.severity === "High" || selected.severity === "Critical" ? "critical" : "warning"}>{selected.severity}</Badge>
                  <StatusBadge status={selected.status} />
                  <Button size="sm" variant="ghost" icon="x" onClick={() => setParam("id", null)}>Close</Button>
                </>
              }
            />
            <div className="grid gap-4 p-4 lg:grid-cols-2">
              <KeyValue
                cols={1}
                items={[
                  ["Driver", state.drivers.find((d) => d.id === selected.driverId)?.name ?? "—"],
                  ["Vehicle", selected.vehicleId ?? "—"],
                  ["Delivery", selected.deliveryId ?? "—"],
                  ["Preventable", selected.preventable ? "Yes" : "No"],
                ]}
              />
              <div className="space-y-3">
                <div>
                  <p className="text-[11.5px] font-bold uppercase tracking-wide text-charcoal-400">Description</p>
                  <p className="mt-1 text-[13.5px] text-charcoal-700">{selected.description}</p>
                </div>
                <div>
                  <p className="text-[11.5px] font-bold uppercase tracking-wide text-charcoal-400">Corrective action</p>
                  <p className="mt-1 text-[13.5px] text-charcoal-700">{selected.correctiveAction || "Not captured yet."}</p>
                </div>
              </div>
            </div>
          </Card>
        </div>
      )}
      <Card>
        <Tabs className="px-3" tabs={["All", "Open", "Under Review", "Closed"].map((t) => ({ key: t, label: t, count: t === "All" ? state.incidents.length : state.incidents.filter((i) => i.status === t).length }))} active={tab} onChange={setTab} />
        <TableWrap>
          <thead><tr><Th>Incident</Th><Th>Type</Th><Th>Date</Th><Th>Time</Th><Th className="hidden md:table-cell">Location</Th><Th className="hidden lg:table-cell">Driver</Th><Th>Vehicle</Th><Th>Severity</Th><Th>Status</Th></tr></thead>
          <tbody>
            {list.map((i) => (
              <Row key={i.id} onClick={() => setParam("id", i.id)}>
                <Td className="font-semibold text-navy-950">{i.id}</Td>
                <Td>{i.type}</Td>
                <Td>{dateSA(i.date)}</Td>
                <Td className="num">{i.time}</Td>
                <Td className="hidden max-w-[200px] truncate md:table-cell">{i.location}</Td>
                <Td className="hidden lg:table-cell">{state.drivers.find((d) => d.id === i.driverId)?.name ?? "—"}</Td>
                <Td>{i.vehicleId ?? "—"}</Td>
                <Td><Badge tone={i.severity === "High" || i.severity === "Critical" ? "critical" : i.severity === "Medium" ? "warning" : "neutral"}>{i.severity}</Badge></Td>
                <Td><StatusBadge status={i.status} /></Td>
              </Row>
            ))}
          </tbody>
        </TableWrap>
        {!list.length && <EmptyState icon="shield" title="No incidents with this status" />}
      </Card>
      <IncidentModal open={open} onClose={() => setOpen(false)} />
    </>
  );
}

/* ====================== NEAR MISSES ====================== */

export function NearMissesPage() {
  const { state } = useStore();
  const [open, setOpen] = useState(false);
  return (
    <>
      <PageHeader
        title="Near Misses"
        description="Close calls reported by drivers. Reporting is blame-free — each report helps prevent a future incident."
        actions={<Button variant="primary" icon="eye" onClick={() => setOpen(true)}>Report near miss</Button>}
      />
      <div className="mb-4">
        <Banner tone="info" icon="info" title="Why near misses matter">
          A near miss is an event that could have caused harm but did not. Recording them lets us fix road, route and
          load risks before somebody is hurt.
        </Banner>
      </div>
      <Card>
        <CardHeader title="Reported near misses" subtitle={`${state.nearMisses.length} reports`} icon="eye" />
        <TableWrap>
          <thead><tr><Th>Reference</Th><Th>Driver</Th><Th>Vehicle</Th><Th>Date</Th><Th>Time</Th><Th>Risk type</Th><Th className="hidden md:table-cell">Location</Th><Th className="hidden lg:table-cell">What happened</Th><Th className="hidden xl:table-cell">Action</Th></tr></thead>
          <tbody>
            {state.nearMisses.map((n) => (
              <Row key={n.id}>
                <Td className="font-semibold text-navy-950">{n.id}</Td>
                <Td>{state.drivers.find((d) => d.id === n.driverId)?.name ?? n.driverId}</Td>
                <Td>{n.vehicleId ?? "—"}</Td>
                <Td>{dateSA(n.date)}</Td>
                <Td className="num">{n.time}</Td>
                <Td><Badge tone="warning">{n.riskType}</Badge></Td>
                <Td className="hidden md:table-cell">{n.location}</Td>
                <Td className="hidden max-w-[260px] truncate lg:table-cell">{n.description}</Td>
                <Td className="hidden max-w-[220px] truncate xl:table-cell">{n.action}</Td>
              </Row>
            ))}
          </tbody>
        </TableWrap>
      </Card>
      <NearMissModal open={open} onClose={() => setOpen(false)} />
    </>
  );
}

/* ====================== INSPECTIONS ====================== */

export function InspectionsPage() {
  const { state } = useStore();
  const [inspectId, setInspectId] = useState<string | null>(null);
  const today = state.inspections.filter((i) => i.date === state.today);
  const pass = today.filter((i) => i.result === "Pass").length;
  const notInspected = state.vehicles.filter((v) => !today.some((i) => i.vehicleId === v.id));

  return (
    <>
      <PageHeader
        title="Vehicle Inspections"
        description="A 13-point check runs before every shift. A failed critical item blocks the vehicle from dispatch until it is resolved."
      />
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <Stat label="Inspections today" value={today.length} icon="clipboard" />
        <Stat label="Passed" value={pass} tone="success" icon="check" />
        <Stat label="Failed" value={today.length - pass} tone={today.length - pass ? "critical" : "success"} icon="warning" />
        <Stat label="Not yet inspected" value={notInspected.length} tone={notInspected.length ? "warning" : "success"} icon="clock" />
      </div>

      {notInspected.length > 0 && (
        <Card className="mt-4">
          <CardHeader title="Vehicles still to inspect today" subtitle="Run the pre-shift check before dispatching these vehicles" icon="warning" />
          <ul className="divide-y divide-mist-100">
            {notInspected.map((v) => (
              <li key={v.id} className="flex items-center gap-3 px-4 py-2.5">
                <span className="w-20 text-[13px] font-bold text-navy-950">{v.id}</span>
                <span className="flex-1 truncate text-[12.5px] text-charcoal-400">{v.model} · {v.registration}</span>
                <StatusBadge status={v.status} />
                <Button size="xs" variant="primary" icon="clipboard" onClick={() => setInspectId(v.id)}>Inspect now</Button>
              </li>
            ))}
          </ul>
        </Card>
      )}

      <Card className="mt-4">
        <CardHeader title="Inspection records" subtitle="Most recent first" icon="list" />
        <ul className="divide-y divide-mist-100">
          {state.inspections.slice(0, 12).map((i) => {
            const failed = i.items.filter((x) => x.result === "Fail");
            return (
              <li key={i.id} className="px-4 py-3">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div>
                    <p className="text-[13.5px] font-semibold text-navy-950">
                      {i.vehicleId} · {dateSA(i.date)} {i.time}
                    </p>
                    <p className="text-[12px] text-charcoal-400">
                      {state.drivers.find((d) => d.id === i.driverId)?.name ?? i.driverId} · odometer {num(i.odometer)} km
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    {i.criticalFail && <Badge tone="critical">Critical failure</Badge>}
                    <StatusBadge status={i.result} />
                  </div>
                </div>
                <div className="mt-2 flex flex-wrap gap-1">
                  {i.items.map((it) => (
                    <span
                      key={it.name}
                      className={cn(
                        "rounded border px-1.5 py-0.5 text-[10.5px] font-semibold",
                        it.result === "Pass" ? "border-mist-200 bg-mist-50 text-charcoal-500" : "border-red-200 bg-red-50 text-red-700",
                      )}
                      title={it.notes}
                    >
                      {it.name} {it.result === "Fail" ? "✕" : "✓"}
                    </span>
                  ))}
                </div>
                {failed.length > 0 && (
                  <p className="mt-2 text-[12.5px] text-red-700">
                    <Icon name="warning" className="mr-1 inline h-3.5 w-3.5" />
                    Failed: {failed.map((f) => f.name).join(", ")}
                  </p>
                )}
              </li>
            );
          })}
        </ul>
      </Card>

      <Card className="mt-4">
        <CardHeader title="Inspection compliance by vehicle" subtitle="Share of vehicles inspected today" icon="target" />
        <div className="p-4">
          <Progress value={(today.length / state.vehicles.length) * 100} />
          <p className="mt-2 text-[12.5px] text-charcoal-400">
            {today.length} of {state.vehicles.length} vehicles inspected today.
          </p>
        </div>
      </Card>

      <InspectionModal vehicleId={inspectId} open={!!inspectId} onClose={() => setInspectId(null)} />
    </>
  );
}
