import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "https://esm.sh/react@19.2.6/jsx-runtime";
import { useState } from "https://esm.sh/react@19.2.6";
import { Donut, HBars, LineChart } from "./../../components/charts.js";
import { Icon } from "./../../components/Icon.js";
import { Badge, Banner, Button, Card, CardHeader, EmptyState, KeyValue, PageHeader, Progress, Row, SimTag, Stat, StatusBadge, Tabs, TableWrap, Td, Th, } from "./../../components/ui.js";
import { IncidentModal, InspectionModal, NearMissModal } from "./../../components/workflow/FleetWorkflows.js";
import { dateSA, num, pct, time24 } from "./../../lib/format.js";
import { useRouter } from "./../../router.js";
import { useStore } from "./../../state/store.js";
import { cn } from "./../../utils/cn.js";
/* ====================== SAFETY DASHBOARD ====================== */
export function SafetyPage() {
    const { state } = useStore();
    const { navigate } = useRouter();
    const [incidentOpen, setIncidentOpen] = useState(false);
    const [nearMissOpen, setNearMissOpen] = useState(false);
    const todayIncidents = state.incidents.filter((i) => i.date === state.today);
    const preventable = state.incidents.filter((i) => i.preventable).length;
    const inspectedToday = state.inspections.filter((i) => i.date === state.today).length;
    const inspectionCompliance = (inspectedToday / state.vehicles.length) * 100;
    const trainingTotal = state.drivers.length * state.drivers[0].training.length;
    const trainingDone = state.drivers.reduce((s, d) => s + d.training.filter((t) => t.status === "Completed").length, 0);
    const trainingCompliance = (trainingDone / trainingTotal) * 100;
    return (_jsxs(_Fragment, { children: [_jsx(PageHeader, { title: "Safety Dashboard", description: "Incidents, near misses, inspection compliance, training and simulated driving events across the fleet.", actions: _jsxs(_Fragment, { children: [_jsx(Button, { variant: "secondary", icon: "eye", onClick: () => setNearMissOpen(true), children: "Report near miss" }), _jsx(Button, { variant: "danger", icon: "shield", onClick: () => setIncidentOpen(true), children: "Report incident" })] }) }), _jsxs("div", { className: "grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6", children: [_jsx(Stat, { label: "Incidents today", value: todayIncidents.length, tone: todayIncidents.length ? "critical" : "success", icon: "alert", onClick: () => navigate("/ops/incidents") }), _jsx(Stat, { label: "Open incidents", value: state.incidents.filter((i) => i.status !== "Closed").length, tone: "warning", icon: "folder", onClick: () => navigate("/ops/incidents") }), _jsx(Stat, { label: "Preventable (all time)", value: preventable, tone: preventable ? "warning" : "success", sub: "target: zero", icon: "target" }), _jsx(Stat, { label: "Near misses logged", value: state.nearMisses.length, icon: "eye", onClick: () => navigate("/ops/near-misses") }), _jsx(Stat, { label: "Inspection compliance", value: pct(inspectionCompliance), tone: inspectionCompliance >= 95 ? "success" : "warning", icon: "clipboard", onClick: () => navigate("/ops/inspections") }), _jsx(Stat, { label: "Training compliance", value: pct(trainingCompliance), tone: trainingCompliance >= 90 ? "success" : "warning", icon: "graduation", onClick: () => navigate("/ops/training") })] }), _jsxs("div", { className: "mt-4 grid gap-4 lg:grid-cols-3", children: [_jsxs(Card, { children: [_jsx(CardHeader, { title: "Incidents by severity", subtitle: "All recorded incidents", icon: "alert" }), _jsx("div", { className: "p-4", children: _jsx(Donut, { segments: ["Low", "Medium", "High", "Critical"].map((s, i) => ({
                                        label: s,
                                        value: state.incidents.filter((x) => x.severity === s).length,
                                        colour: ["#12a05c", "#d97706", "#dc2626", "#7f1d1d"][i],
                                    })), centreValue: String(state.incidents.length), centreLabel: "incidents" }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { title: "Near misses by risk type", subtitle: "Reporting is blame-free and encouraged", icon: "eye" }), _jsx("div", { className: "p-4", children: _jsx(HBars, { data: Array.from(new Set(state.nearMisses.map((n) => n.riskType))).map((t) => ({
                                        label: t,
                                        value: state.nearMisses.filter((n) => n.riskType === t).length,
                                    })), colour: "#2b5480" }) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { title: "Safety events trend", subtitle: "Daily incidents over 30 days", icon: "activity" }), _jsx("div", { className: "p-4", children: _jsx(LineChart, { data: state.history.map((h) => ({ label: h.date.slice(8), value: h.incidents })), height: 170, colour: "#dc2626", yMin: 0, yMax: 3 }) })] })] }), _jsxs("div", { className: "mt-4 grid gap-4 lg:grid-cols-2", children: [_jsxs(Card, { children: [_jsx(CardHeader, { title: "Simulated telematics events", subtitle: "Speed, braking and acceleration events generated by the demo", icon: "signal", action: _jsx(SimTag, {}) }), _jsxs(TableWrap, { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx(Th, { children: "Vehicle" }), _jsx(Th, { children: "Event" }), _jsx(Th, { children: "Value" }), _jsx(Th, { children: "Location" }), _jsx(Th, { children: "Time" })] }) }), _jsx("tbody", { children: state.telematics.slice(0, 10).map((t) => (_jsxs(Row, { children: [_jsx(Td, { className: "font-semibold text-navy-950", children: t.vehicleId }), _jsx(Td, { children: _jsx(Badge, { tone: t.type === "Speeding" || t.type === "Harsh Braking" ? "warning" : "neutral", children: t.type }) }), _jsx(Td, { className: "num", children: t.value }), _jsx(Td, { children: t.location }), _jsx(Td, { className: "num", children: time24(t.time) })] }, t.id))) })] })] }), _jsxs(Card, { children: [_jsx(CardHeader, { title: "Corrective actions", subtitle: "What is being done about recorded incidents", icon: "clipboard" }), _jsx("ul", { className: "divide-y divide-mist-100", children: state.incidents.map((i) => (_jsxs("li", { className: "px-4 py-3", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-2", children: [_jsxs("button", { onClick: () => navigate(`/ops/incidents?id=${i.id}`), className: "text-[13px] font-semibold text-navy-950 hover:underline", children: [i.id, " \u00B7 ", i.type] }), _jsx(StatusBadge, { status: i.status })] }), _jsx("p", { className: "mt-1 text-[12.5px] text-charcoal-500", children: i.correctiveAction || "Corrective action still to be captured." })] }, i.id))) })] })] }), _jsx(IncidentModal, { open: incidentOpen, onClose: () => setIncidentOpen(false) }), _jsx(NearMissModal, { open: nearMissOpen, onClose: () => setNearMissOpen(false) })] }));
}
/* ====================== INCIDENTS ====================== */
export function IncidentsPage() {
    const { state } = useStore();
    const { params, setParam } = useRouter();
    const [open, setOpen] = useState(false);
    const [tab, setTab] = useState("All");
    const selected = state.incidents.find((i) => i.id === params.get("id"));
    const list = state.incidents.filter((i) => tab === "All" || i.status === tab);
    return (_jsxs(_Fragment, { children: [_jsx(PageHeader, { title: "Incidents", description: "Every safety incident recorded against a driver, vehicle or delivery, with severity and corrective action.", actions: _jsx(Button, { variant: "danger", icon: "shield", onClick: () => setOpen(true), children: "Report incident" }) }), selected && (_jsx("div", { className: "mb-4", children: _jsxs(Card, { children: [_jsx(CardHeader, { title: `${selected.id} · ${selected.type}`, subtitle: `${dateSA(selected.date)} ${selected.time} · ${selected.location}`, icon: "alert", action: _jsxs(_Fragment, { children: [_jsx(Badge, { tone: selected.severity === "High" || selected.severity === "Critical" ? "critical" : "warning", children: selected.severity }), _jsx(StatusBadge, { status: selected.status }), _jsx(Button, { size: "sm", variant: "ghost", icon: "x", onClick: () => setParam("id", null), children: "Close" })] }) }), _jsxs("div", { className: "grid gap-4 p-4 lg:grid-cols-2", children: [_jsx(KeyValue, { cols: 1, items: [
                                        ["Driver", state.drivers.find((d) => d.id === selected.driverId)?.name ?? "—"],
                                        ["Vehicle", selected.vehicleId ?? "—"],
                                        ["Delivery", selected.deliveryId ?? "—"],
                                        ["Preventable", selected.preventable ? "Yes" : "No"],
                                    ] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-[11.5px] font-bold uppercase tracking-wide text-charcoal-400", children: "Description" }), _jsx("p", { className: "mt-1 text-[13.5px] text-charcoal-700", children: selected.description })] }), _jsxs("div", { children: [_jsx("p", { className: "text-[11.5px] font-bold uppercase tracking-wide text-charcoal-400", children: "Corrective action" }), _jsx("p", { className: "mt-1 text-[13.5px] text-charcoal-700", children: selected.correctiveAction || "Not captured yet." })] })] })] })] }) })), _jsxs(Card, { children: [_jsx(Tabs, { className: "px-3", tabs: ["All", "Open", "Under Review", "Closed"].map((t) => ({ key: t, label: t, count: t === "All" ? state.incidents.length : state.incidents.filter((i) => i.status === t).length })), active: tab, onChange: setTab }), _jsxs(TableWrap, { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx(Th, { children: "Incident" }), _jsx(Th, { children: "Type" }), _jsx(Th, { children: "Date" }), _jsx(Th, { children: "Time" }), _jsx(Th, { className: "hidden md:table-cell", children: "Location" }), _jsx(Th, { className: "hidden lg:table-cell", children: "Driver" }), _jsx(Th, { children: "Vehicle" }), _jsx(Th, { children: "Severity" }), _jsx(Th, { children: "Status" })] }) }), _jsx("tbody", { children: list.map((i) => (_jsxs(Row, { onClick: () => setParam("id", i.id), children: [_jsx(Td, { className: "font-semibold text-navy-950", children: i.id }), _jsx(Td, { children: i.type }), _jsx(Td, { children: dateSA(i.date) }), _jsx(Td, { className: "num", children: i.time }), _jsx(Td, { className: "hidden max-w-[200px] truncate md:table-cell", children: i.location }), _jsx(Td, { className: "hidden lg:table-cell", children: state.drivers.find((d) => d.id === i.driverId)?.name ?? "—" }), _jsx(Td, { children: i.vehicleId ?? "—" }), _jsx(Td, { children: _jsx(Badge, { tone: i.severity === "High" || i.severity === "Critical" ? "critical" : i.severity === "Medium" ? "warning" : "neutral", children: i.severity }) }), _jsx(Td, { children: _jsx(StatusBadge, { status: i.status }) })] }, i.id))) })] }), !list.length && _jsx(EmptyState, { icon: "shield", title: "No incidents with this status" })] }), _jsx(IncidentModal, { open: open, onClose: () => setOpen(false) })] }));
}
/* ====================== NEAR MISSES ====================== */
export function NearMissesPage() {
    const { state } = useStore();
    const [open, setOpen] = useState(false);
    return (_jsxs(_Fragment, { children: [_jsx(PageHeader, { title: "Near Misses", description: "Close calls reported by drivers. Reporting is blame-free \u2014 each report helps prevent a future incident.", actions: _jsx(Button, { variant: "primary", icon: "eye", onClick: () => setOpen(true), children: "Report near miss" }) }), _jsx("div", { className: "mb-4", children: _jsx(Banner, { tone: "info", icon: "info", title: "Why near misses matter", children: "A near miss is an event that could have caused harm but did not. Recording them lets us fix road, route and load risks before somebody is hurt." }) }), _jsxs(Card, { children: [_jsx(CardHeader, { title: "Reported near misses", subtitle: `${state.nearMisses.length} reports`, icon: "eye" }), _jsxs(TableWrap, { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx(Th, { children: "Reference" }), _jsx(Th, { children: "Driver" }), _jsx(Th, { children: "Vehicle" }), _jsx(Th, { children: "Date" }), _jsx(Th, { children: "Time" }), _jsx(Th, { children: "Risk type" }), _jsx(Th, { className: "hidden md:table-cell", children: "Location" }), _jsx(Th, { className: "hidden lg:table-cell", children: "What happened" }), _jsx(Th, { className: "hidden xl:table-cell", children: "Action" })] }) }), _jsx("tbody", { children: state.nearMisses.map((n) => (_jsxs(Row, { children: [_jsx(Td, { className: "font-semibold text-navy-950", children: n.id }), _jsx(Td, { children: state.drivers.find((d) => d.id === n.driverId)?.name ?? n.driverId }), _jsx(Td, { children: n.vehicleId ?? "—" }), _jsx(Td, { children: dateSA(n.date) }), _jsx(Td, { className: "num", children: n.time }), _jsx(Td, { children: _jsx(Badge, { tone: "warning", children: n.riskType }) }), _jsx(Td, { className: "hidden md:table-cell", children: n.location }), _jsx(Td, { className: "hidden max-w-[260px] truncate lg:table-cell", children: n.description }), _jsx(Td, { className: "hidden max-w-[220px] truncate xl:table-cell", children: n.action })] }, n.id))) })] })] }), _jsx(NearMissModal, { open: open, onClose: () => setOpen(false) })] }));
}
/* ====================== INSPECTIONS ====================== */
export function InspectionsPage() {
    const { state } = useStore();
    const [inspectId, setInspectId] = useState(null);
    const today = state.inspections.filter((i) => i.date === state.today);
    const pass = today.filter((i) => i.result === "Pass").length;
    const notInspected = state.vehicles.filter((v) => !today.some((i) => i.vehicleId === v.id));
    return (_jsxs(_Fragment, { children: [_jsx(PageHeader, { title: "Vehicle Inspections", description: "A 13-point check runs before every shift. A failed critical item blocks the vehicle from dispatch until it is resolved." }), _jsxs("div", { className: "grid grid-cols-2 gap-3 lg:grid-cols-4", children: [_jsx(Stat, { label: "Inspections today", value: today.length, icon: "clipboard" }), _jsx(Stat, { label: "Passed", value: pass, tone: "success", icon: "check" }), _jsx(Stat, { label: "Failed", value: today.length - pass, tone: today.length - pass ? "critical" : "success", icon: "warning" }), _jsx(Stat, { label: "Not yet inspected", value: notInspected.length, tone: notInspected.length ? "warning" : "success", icon: "clock" })] }), notInspected.length > 0 && (_jsxs(Card, { className: "mt-4", children: [_jsx(CardHeader, { title: "Vehicles still to inspect today", subtitle: "Run the pre-shift check before dispatching these vehicles", icon: "warning" }), _jsx("ul", { className: "divide-y divide-mist-100", children: notInspected.map((v) => (_jsxs("li", { className: "flex items-center gap-3 px-4 py-2.5", children: [_jsx("span", { className: "w-20 text-[13px] font-bold text-navy-950", children: v.id }), _jsxs("span", { className: "flex-1 truncate text-[12.5px] text-charcoal-400", children: [v.model, " \u00B7 ", v.registration] }), _jsx(StatusBadge, { status: v.status }), _jsx(Button, { size: "xs", variant: "primary", icon: "clipboard", onClick: () => setInspectId(v.id), children: "Inspect now" })] }, v.id))) })] })), _jsxs(Card, { className: "mt-4", children: [_jsx(CardHeader, { title: "Inspection records", subtitle: "Most recent first", icon: "list" }), _jsx("ul", { className: "divide-y divide-mist-100", children: state.inspections.slice(0, 12).map((i) => {
                            const failed = i.items.filter((x) => x.result === "Fail");
                            return (_jsxs("li", { className: "px-4 py-3", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-2", children: [_jsxs("div", { children: [_jsxs("p", { className: "text-[13.5px] font-semibold text-navy-950", children: [i.vehicleId, " \u00B7 ", dateSA(i.date), " ", i.time] }), _jsxs("p", { className: "text-[12px] text-charcoal-400", children: [state.drivers.find((d) => d.id === i.driverId)?.name ?? i.driverId, " \u00B7 odometer ", num(i.odometer), " km"] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [i.criticalFail && _jsx(Badge, { tone: "critical", children: "Critical failure" }), _jsx(StatusBadge, { status: i.result })] })] }), _jsx("div", { className: "mt-2 flex flex-wrap gap-1", children: i.items.map((it) => (_jsxs("span", { className: cn("rounded border px-1.5 py-0.5 text-[10.5px] font-semibold", it.result === "Pass" ? "border-mist-200 bg-mist-50 text-charcoal-500" : "border-red-200 bg-red-50 text-red-700"), title: it.notes, children: [it.name, " ", it.result === "Fail" ? "✕" : "✓"] }, it.name))) }), failed.length > 0 && (_jsxs("p", { className: "mt-2 text-[12.5px] text-red-700", children: [_jsx(Icon, { name: "warning", className: "mr-1 inline h-3.5 w-3.5" }), "Failed: ", failed.map((f) => f.name).join(", ")] }))] }, i.id));
                        }) })] }), _jsxs(Card, { className: "mt-4", children: [_jsx(CardHeader, { title: "Inspection compliance by vehicle", subtitle: "Share of vehicles inspected today", icon: "target" }), _jsxs("div", { className: "p-4", children: [_jsx(Progress, { value: (today.length / state.vehicles.length) * 100 }), _jsxs("p", { className: "mt-2 text-[12.5px] text-charcoal-400", children: [today.length, " of ", state.vehicles.length, " vehicles inspected today."] })] })] }), _jsx(InspectionModal, { vehicleId: inspectId, open: !!inspectId, onClose: () => setInspectId(null) })] }));
}
